from tir import Webapp
import unittest

class GTPA408(unittest.TestCase):

        @classmethod
        def setUpClass(inst):
                inst.oHelper = Webapp()
                inst.oHelper.Setup('SIGAGTP', '07/05/2020', 'T1', 'D MG 01 ', '88')
                inst.oHelper.Program('GTPA408')

        def test_GTPA408_CT001(self):
                self.oHelper.SetButton('Assistente')
                self.oHelper.SetBranch('D MG 01')
                self.oHelper.WaitShow('Assistente de Configuração')
                self.oHelper.SetButton('Avançar')

                ''' testes com opções de filtro''' 
                self.oHelper.SetValue("GY4_DATADE",'07/05/2020')
                self.oHelper.SetValue("GY4_DATATE",'14/05/2020')
                self.oHelper.SetValue("GY4_FILTRO",'2')
                self.oHelper.SetValue("GY4_LOCDE",'LOC029')
                self.oHelper.SetValue("GY4_LOCATE",'LOC029')
                self.oHelper.SetValue("GY4_TPFILT",'1')
                self.oHelper.SetButton('Avançar')
                self.oHelper.SetButton('Voltar')
                self.oHelper.SetValue("GY4_DATADE",'07/05/2020')
                self.oHelper.SetValue("GY4_DATATE",'14/05/2020')
                self.oHelper.SetValue("GY4_FILTRO",'1')
                self.oHelper.SetValue("GY4_SETOR",'000001')
                self.oHelper.SetValue("GY4_LOCDE",'')
                self.oHelper.SetValue("GY4_LOCATE",'')
                self.oHelper.SetValue("GY4_TPFILT",'1')
                self.oHelper.SetButton('Avançar')
                self.oHelper.SetButton('Sim')
                self.oHelper.SetButton('Voltar')
                self.oHelper.SetValue("GY4_DATADE",'07/05/2020')
                self.oHelper.SetValue("GY4_DATATE",'14/05/2020')
                self.oHelper.SetValue("GY4_FILTRO",'1')
                self.oHelper.SetValue("GY4_SETOR",'000001')
                self.oHelper.SetValue("GY4_LOCDE",'')
                self.oHelper.SetValue("GY4_LOCATE",'')
                self.oHelper.SetValue("GY4_TPFILT",'2')
                self.oHelper.SetButton('Avançar')
                self.oHelper.SetButton('Sim')
                self.oHelper.SetButton('Voltar')
                self.oHelper.SetValue("GY4_DATADE",'07/05/2020')
                self.oHelper.SetValue("GY4_DATATE",'14/05/2020')
                self.oHelper.SetValue("GY4_FILTRO",'2')
                self.oHelper.SetValue("GY4_LOCDE",'LOC029')
                self.oHelper.SetValue("GY4_LOCATE",'LOC029')
                self.oHelper.SetValue("GY4_TPFILT",'2')
                self.oHelper.SetButton('Avançar')
                self.oHelper.SetButton('Sim')

                ''' teste de seleção de horários e seccionamento '''
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.ScrollGrid(column='Cod.Horario', match_value='00000000015', grid_number=1)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.SetKey('F5')
                self.oHelper.ScrollGrid(column='Horário', match_value='00000000015', grid_number=2)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetKey('F7')
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.ScrollGrid(column='Cod.Horario', match_value='00000000015', grid_number=1)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetKey('F5')
                self.oHelper.ScrollGrid(column='Horário', match_value='00000000015', grid_number=2)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetKey('F8')
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.ClickGridHeader(column_name="Cod.Horario")
                self.oHelper.ClickGridHeader(column_name="Cod.Horario")
                self.oHelper.ScrollGrid(column='Cod.Horario', match_value='00000000014', grid_number=1)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.SetKey('F5')
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.ClickGridHeader(column_name="Cod.Horario")
                self.oHelper.ScrollGrid(column='Cod.Horario', match_value='00000000015', grid_number=1)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetKey('F5')
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.ScrollGrid(column='Horário', match_value='00000000014', grid_number=2)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.SetKey('F8')
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.ScrollGrid(column='Cod.Horario', match_value='00000000015', grid_number=1)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.SetKey('F6')
                self.oHelper.SetButton('Sim')
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.ClickGridHeader(column_name="Origem/Destino")
                self.oHelper.ClickGridHeader(column_name="Origem/Destino")
                self.oHelper.ClickGridHeader(column_name="Origem/Destino")
                self.oHelper.ClickGridHeader(column_name="Origem/Destino")
                self.oHelper.ScrollGrid(column='Origem/Destino', match_value='BRAGANCA PAULISTA -CASO DE TESTE GTPA408/ATIBAIA - CASO DE TESTE GTPA408', grid_number=1)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.SetKey('F5')
                self.oHelper.SetValue("Descr. Escala",'automacao')
                self.oHelper.ClickGridHeader(column_name="Cod.Horario")
                self.oHelper.ClickGridHeader(column_name="Cod.Horario")
                self.oHelper.ScrollGrid(column='Cod.Horario', match_value='00000000014', grid_number=1)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.SetKey('F6')
                self.oHelper.SetButton('Sim')
                self.oHelper.ScrollGrid(column='Cod.Horario', match_value='00000000014', grid_number=1)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.SetKey('F6')
                self.oHelper.SetButton('Não')
                self.oHelper.ScrollGrid(column='Cod.Horario', match_value='00000000014', grid_number=1)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.SetKey('F6')
                self.oHelper.SetButton('Sim')
                self.oHelper.ScrollGrid(column='Cod.Horario', match_value='00000000014', grid_number=1)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.SetKey('F6')
                self.oHelper.SetButton('Sim')
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.ClickGridHeader(column_name="Origem/Destino")
                self.oHelper.ClickGridHeader(column_name="Origem/Destino")
                self.oHelper.ScrollGrid(column='Origem/Destino', match_value='SAO PAULO - CASO DE TESTE GTPA408/ATIBAIA - CASO DE TESTE GTPA408', grid_number=1)
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.SetKey('F5')
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.ScrollGrid(column='Seq', match_value='0002', grid_number=2)
                self.oHelper.SetValue("D", False, grid=True, grid_number=2)
                self.oHelper.LoadGrid()
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.ScrollGrid(column='Seq', match_value='0002', grid_number=2)
                self.oHelper.SetValue("D", True, grid=True, grid_number=2)
                self.oHelper.SetValue("D", True, grid=True, grid_number=2)
                self.oHelper.LoadGrid()
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.ScrollGrid(column='Seq', match_value='0004', grid_number=2)
                self.oHelper.SetValue("Dia", '3', grid=True, grid_number=2)
                self.oHelper.LoadGrid()
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.ScrollGrid(column='Seq', match_value='0004', grid_number=2)
                self.oHelper.SetValue("Dia", '2', grid=True, grid_number=2)
                self.oHelper.LoadGrid()
                self.oHelper.SetFocus("Descr. Escala")
                self.oHelper.SetValue("Descr. Escala",'AUTOMACAO GTPA408')
                self.oHelper.SetValue("Local Manut.",'LOC031')
                self.oHelper.SetButton('Avançar')

                ''' seleçao de veiculos '''
                self.oHelper.SetButton('Concluir')
                self.oHelper.SetButton('Fechar')
                self.oHelper.SetFocus('Veículo',grid_cell=True,row_number=1)
                self.oHelper.SetKey('F6')
                self.oHelper.ScrollGrid(column='Caract.', match_value='GTP001', grid_number=1)
                self.oHelper.SetButton('Fechar')
                self.oHelper.ScrollGrid(column='Veículo', match_value='VEICULOGTP_011')
                self.oHelper.SetValue("Check", True, grid=True, grid_number=1)
                self.oHelper.LoadGrid()
                self.oHelper.ScrollGrid(column='Veículo', match_value='VEICULOGTP_012')
                self.oHelper.SetValue("Check", True, grid=True, grid_number=1)
                self.oHelper.LoadGrid()
                self.oHelper.ScrollGrid(column='Veículo', match_value='VEICULOGTP_012')
                self.oHelper.SetButton('Concluir')

                ''' visualização da escala '''
                self.oHelper.SetButton('Visualizar')
                self.oHelper.SetButton('Outras Ações','Seccionado')
                self.oHelper.SetButton('Fechar')
                self.oHelper.SetButton('Fechar')
                self.oHelper.LoadGrid()

                ''' alteração da escala '''
                self.oHelper.SetButton('Alterar')
                self.oHelper.SetButton('Avançar')
                self.oHelper.SetButton('Avançar')
                self.oHelper.SetButton('Avançar')
                self.oHelper.SetButton('Concluir')
                self.oHelper.AssertTrue()

        @classmethod
        def tearDownClass(inst):
                inst.oHelper.TearDown()
                

if __name__ == '__main__':
        unittest.main()
