from tir import Webapp
import unittest

class GTPA900(unittest.TestCase):

	@classmethod
	def setUpClass(inst):
		inst.oHelper = Webapp()
		inst.oHelper.Setup("SIGAGTP", "02/12/2020", "T1", "D MG 01 ")
		inst.oHelper.Program('GTPA900')

	def test_GTPA900_CT001(self):
    	#---------------------------------INCLUIR-------------------------------------#
		#----------------------------CABEÇALHO CADASTRAL------------------------------#
		self.oHelper.SetButton("Incluir")
		self.oHelper.SetButton("OK")
		self.oHelper.SetValue('Data Inicio','02/12/2020')
		self.oHelper.SetValue('Un. Vigência','2')
		self.oHelper.SetValue('Vigência','90')
		self.oHelper.SetValue('Cond. Pagto.','000')
		self.oHelper.SetValue('Tp. Contrato','001')
		self.oHelper.SetValue('Cod. Cliente','GTP001')
		self.oHelper.SetValue('Loja','01')
		self.oHelper.SetValue('Cod Vendedor','GTP001')
		self.oHelper.SetValue('Produto','GTP003')
		self.oHelper.SetValue('Tp. Planilha','000')
		self.oHelper.SetValue('Tab. Preço','001')
		#---------------------------GRID CUSTOS ADICIONAIS----------------------------#
		self.oHelper.ClickGridCell("Custo Unit.", row=1, grid_number=1)
		self.oHelper.SetValue('Custo Unit.', '600,00', grid=True, grid_number=1)
		self.oHelper.LoadGrid()	
		self.oHelper.ClickGridCell("Unidade", row=1, grid_number=1)
		self.oHelper.SetValue('Unidade', 'SV', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Quantidade", row=1, grid_number=1)
		self.oHelper.SetValue('Quantidade', '1', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		#--------------------------GRID 1 DADOS DA LINHA------------------------------#
		self.oHelper.ClickFolder("Precificaçao / Itinerário")
		self.oHelper.ClickGridCell("Cód. Órgão", row=1, grid_number=1)
		self.oHelper.SetValue('Cód. Órgão', 'GTP001', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Produto", row=1, grid_number=1)
		self.oHelper.SetValue('Produto', 'GTP003', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Produto", row=1, grid_number=1)
		self.oHelper.SetValue('Produto', 'GTP003', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Loc. Início", row=1, grid_number=1)
		self.oHelper.SetValue('Loc. Início', 'LOC001', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Loc. Início", row=1, grid_number=1)
		self.oHelper.SetValue('Loc. Início', 'LOC001', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("KM Ida", row=1, grid_number=1)
		self.oHelper.SetValue('KM Ida', '50,00', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Loc. Final", row=1, grid_number=1)
		self.oHelper.SetValue('Loc. Final', 'LOC002', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("KM Volta", row=1, grid_number=1)
		self.oHelper.SetValue('KM Volta', '60,00', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("KM Gar./Rod.", row=1, grid_number=1)
		self.oHelper.SetValue('KM Gar./Rod.', '10,00', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("KM Rod./Gar.", row=1, grid_number=1)
		self.oHelper.SetValue('KM Rod./Gar.', '10,00', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Tp. Operaçao", row=1, grid_number=1)
		self.oHelper.SetValue('Tp. Operaçao', '1', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Ano do Carro", row=1, grid_number=1)
		self.oHelper.SetValue('Ano do Carro', '2.019', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Tp. Pre. Con", row=1, grid_number=1)
		self.oHelper.SetValue('Tp. Pre. Con', '1', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Precif.Extra", row=1, grid_number=1)
		self.oHelper.SetValue('Precif.Extra', '2', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Total linha", row=1, grid_number=1)
		self.oHelper.SetValue('Total linha', '700,00', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Inic.Vigenc", row=1, grid_number=1)
		self.oHelper.SetValue('Inic.Vigenc', '02/12/2020', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Final Vigenc", row=1, grid_number=1)
		self.oHelper.SetValue('Final Vigenc', '02/12/2021', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Lotacao", row=1, grid_number=1)
		self.oHelper.SetValue('Lotacao', '44', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		#--------------------------LISTAGEM DE PASSAGEIROS------------------------------#
		self.oHelper.SetButton("Outras Ações", "Listagem passageiros")
		self.oHelper.SetValue('Descriçao', 'Teste')
		self.oHelper.SetValue('Observaçao', 'Teste aut')		
		self.oHelper.ClickGridCell("Nome", row=1, grid_number=1)
		self.oHelper.SetValue('Nome', 'Marcos teste', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("CPF", row=1, grid_number=1)
		self.oHelper.SetValue('CPF', '79018151084', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("CEP", row=1, grid_number=1)
		self.oHelper.SetValue('CEP', '00000000', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Endereço", row=1, grid_number=1)
		self.oHelper.SetValue('Endereço', 'B', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Complemento", row=1, grid_number=1)
		self.oHelper.SetValue('Complemento', 'C', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Bairro", row=1, grid_number=1)
		self.oHelper.SetValue('Bairro', 'D', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Municipio", row=1, grid_number=1)
		self.oHelper.SetValue('Municipio', 'SP', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.ClickGridCell("Estado", row=1, grid_number=1)
		self.oHelper.SetValue('Estado', 'SP', grid=True, grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.SetButton("Confirmar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Confirmar")
		self.oHelper.SetButton("Fechar")
		#---------------------------------ALTERAÇÃO-------------------------------------#
		#----------------------------CABEÇALHO CADASTRAL--------------------------------#
		self.oHelper.SetButton("Alterar")
		self.oHelper.SetValue('Franquia KM', '40')
		self.oHelper.SetButton("Confirmar")
		self.oHelper.SetButton("Fechar")
		#---------------------------------VISUALIZAÇÃO----------------------------------#
		self.oHelper.SetButton("Visualizar")
		self.oHelper.SetButton("Fechar")
		#---------------------------------EXCLUSÃO--------------------------------------#
		self.oHelper.SetButton("Outras Ações", "Excluir")
		self.oHelper.SetButton("Confirmar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.AssertTrue()

	@classmethod
	def tearDownClass(inst):
		inst.oHelper.TearDown()	

if __name__ == '__main__':
	unittest.main()
