from tir import Webapp
import unittest

class JURA020(unittest.TestCase):

	@classmethod
	def setUpClass(inst):
		inst.oHelper = Webapp()
		inst.oHelper.Setup('SIGAJURI','12/11/2018','T1','D MG 01 ','05')
		inst.oHelper.Program('JURA020')
		inst.oHelper.AddParameter("MV_JTPIMP", "", "2", "", "")
		inst.oHelper.AddParameter("MV_JPUBTOT", "", "1", "", "")
		inst.oHelper.AddParameter("MV_JNT4CLI", "", "1", "", "")
		inst.oHelper.SetParameters()

	def test_JURA020_CT001(self):

		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/04/2016",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","30/04/2016",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.SetButton("Outras Ações","Filtrar por Palavra-chave")
		self.oHelper.ClickBox("Palavra-Chave","GENILSON")
		self.oHelper.SetButton("Filtrar")
		self.oHelper.ClickFolder("Publicações não Localizadas")
		self.oHelper.ClickBox("Num.Proc.","3001565-81.2013.8.26.0554")
		self.oHelper.SetButton("Outras Ações","Vincular Processo")
		self.oHelper.SetButton("Sim")
		self.oHelper.SetValue("cProces","777777777777777777",name_attr=True)
		self.oHelper.SetButton("Pesquisar")
		self.oHelper.SetValue("cAutor","01",name_attr=True)
		self.oHelper.ClickGridCell("Cód.Interno",row=1)
		self.oHelper.ClickBox("Cód.Interno","0000000081")
		self.oHelper.SetButton("Ok")
		self.oHelper.SetButton("Sim")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da Página")
		self.oHelper.SetLateralMenu("Atualizações > Assuntos Jurídicos > Pesquisas")
		self.oHelper.SetValue("cValor","Contencioso",name_attr=True)
		self.oHelper.WaitFieldValue("NSZ_COD","")
		self.oHelper.SetValue("NSZ_COD","0000000081")
		self.oHelper.ClickLabel("Pesquisar")
		self.oHelper.ClickGridCell("Código do cliente",row=1)
		self.oHelper.ClickLabel("Visualizar")
		self.oHelper.CheckResult("NSZ_NUMPRO","3001565-81.2013.8.26.0554")
		self.oHelper.CheckResult("NSZ_COD","0000000081")
		self.oHelper.SetButton("Fechar")
		self.oHelper.ClickLabel("Sair")
		self.oHelper.SetLateralMenu("Importação de Publicações")
		self.oHelper.SetButton("Executar")
		self.oHelper.SetButton("Outras Ações","Filtrar por Palavra-chave")
		self.oHelper.ClickBox("Palavra-Chave","MENEGHINI")
		self.oHelper.SetButton("Filtrar")
		self.oHelper.ClickFolder("Publicações Localizadas")
		self.oHelper.ClickBox("Num.Proc","1001264-51.2016.8.26.0268")
		self.oHelper.SetButton("Outras Ações","Conciliar Manual")
		self.oHelper.SetButton("Sim")
		self.oHelper.SetValue("cCodAto","008",name_attr=True)
		self.oHelper.SetButton("Ok")
		self.oHelper.SetButton("Ok")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da Página")
		self.oHelper.SetLateralMenu("Pesquisas")
		self.oHelper.SetValue("cValor","Contencioso",name_attr=True)
		self.oHelper.WaitFieldValue("NSZ_COD","")
		self.oHelper.SetValue("NSZ_COD","0000000004")
		self.oHelper.ClickLabel("Pesquisar")
		self.oHelper.ClickGridCell("Código do cliente",row=1)
		self.oHelper.ClickLabel("Visualizar")
		self.oHelper.CheckResult("NSZ_COD","0000000004")
		self.oHelper.SetButton("Andamentos")
		self.oHelper.SetButton("Visualizar")
		self.oHelper.CheckResult("NT4_CAJURI","0000000004")
		self.oHelper.CheckResult("NT4_CATO","008")
		self.oHelper.SetButton("Fechar")
		self.oHelper.AssertTrue()
		self.oHelper.RestoreParameters()

	@classmethod
	def tearDownClass(inst):
		inst.oHelper.TearDown()

if __name__ == '__main__':
	unittest.main()
