from tir import Webapp
import unittest


class JURA219(unittest.TestCase):

	@classmethod
	def setUpClass(inst):
		inst.oHelper = Webapp()
		inst.oHelper.Setup('SIGAJURI','24/10/2018','T1','D MG 01 ','76')

	def test_JURA219_CT001(self):

		print("CT001 - Gera o relatório de distribuicoes recebidas")
		self.oHelper.Program('JURA219')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","31/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR04","001",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.ClickFolder("Distribuições recebidas")
		self.oHelper.SetButton("Outras Ações","Exportar Recebidas")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da página")
		self.oHelper.AssertTrue()

	def test_JURA219_CT002(self):

		print("CT002 - Cadastra a palavra chave HAYAS")
		self.oHelper.Program('JURA219')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","31/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR04","001",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.SetButton("Outras Ações","Palavra Chave")
		self.oHelper.SetButton("Incluir")
		self.oHelper.SetValue("NS8_DESCHV","HAYAS")
		self.oHelper.SetButton("Confirmar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("X")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da página")
		self.oHelper.AssertTrue()

	def test_JURA219_CT003(self):

		print("CT003 - Filtra as distribuicoes por palavra chave")
		self.oHelper.Program('JURA219')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","31/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR04","001",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.SetButton("Filtrar Distribuições")
		self.oHelper.ClickBox("Palavra - Chave","HAYAS")
		self.oHelper.SetButton("Filtrar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da página")
		self.oHelper.AssertTrue()

	def test_JURA219_CT004(self):

		print("CT004 -  Cria o model JURA219 - MODELO CT003")
		self.oHelper.Program('JURA219')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","31/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR04","001",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.ClickFolder("Campos Obrigatórios")
		self.oHelper.SetValue("NSZ_CCLIEN","JUR219")
		self.oHelper.SetValue("NSZ_LCLIEN","19")
		self.oHelper.SetValue("NSZ_CESCRI","SP001")
		self.oHelper.SetValue("NSZ_CAREAJ","00004")
		self.oHelper.SetValue("NSZ_SIGLA1","CRS")
		self.oHelper.SetValue("NSZ_CFCORR","04")
		self.oHelper.ClickGridCell("Cód Natureza",row=1,grid_number=2)
		self.oHelper.SetValue("NUQ_CNATUR","001",grid=True,grid_number=2)
		self.oHelper.SetValue("NUQ_CTIPAC","001",grid=True,grid_number=2)
		self.oHelper.SetValue("NUQ_CCOMAR","0001",grid=True,grid_number=2)
		self.oHelper.SetValue("NUQ_CLOC2N","00001",grid=True,grid_number=2)
		self.oHelper.SetValue("NUQ_CLOC3N","00001",grid=True,grid_number=2)
		self.oHelper.LoadGrid()
		self.oHelper.ClickFolder("Andamentos \\ Follow-ups")
		self.oHelper.ClickGridCell("Cód Ato",grid_number=1)
		self.oHelper.SetValue("NT4_CATO","008",grid=True,grid_number=1)
		self.oHelper.SetValue("NT4_DESC","CT004 -  Cria o model JURA219 - MODELO CT003",grid=True,grid_number=1)
		self.oHelper.LoadGrid()
		self.oHelper.SetButton("Salvar Modelo")
		self.oHelper.SetValue("cRet","JURA219 - MODELO CT003",name_attr=True)
		self.oHelper.SetButton("Ok")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da página")
		self.oHelper.AssertTrue()

	def test_JURA219_CT005(self):

		print("CT005 - Carrega o modelo criado anteriormente e limpa a tela")
		self.oHelper.Program('JURA219')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","31/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR04","001",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")	
		self.oHelper.ClickFolder("Campos Obrigatórios")
		self.oHelper.SetButton("Carregar Modelo")
		self.oHelper.SetButton("Sim")
		self.oHelper.SearchBrowse("JURA219 - MODELO CT003", key=3, index=True)
		self.oHelper.SetButton("Confirma")
		self.oHelper.SetButton("Outras Ações","Limpa Tela")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da página")
		self.oHelper.AssertTrue()

	def test_JURA219_CT006(self):

		print("CT006 - Abre o documento em anexo da distribuição 0000000001")
		self.oHelper.Program('JURA219')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","31/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR04","001",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")	
		self.oHelper.ClickFolder("Distribuições importadas")
		self.oHelper.ClickFolder("Distribuições recebidas")
		self.oHelper.ClickBox("Código","0000000001")
		self.oHelper.SetButton("Outras Ações","Abrir Documentos")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da página")
		self.oHelper.AssertTrue()

	def test_JURA219_CT007(self):

		print("CT007 - Exclusão da distribuição 0000000002")
		self.oHelper.Program('JURA219')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","31/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR04","001",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.ClickFolder("Distribuições importadas")
		self.oHelper.ClickFolder("Distribuições recebidas")
		self.oHelper.ClickGridCell("Código",row=1)
		self.oHelper.ClickBox("Código","0000000002")
		self.oHelper.SetButton("Outras Ações","Excluir")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da página")
		self.oHelper.AssertTrue()

	def test_JURA219_CT008(self):

		print("CT008 - Restaura a distribuicao excluida anteriormente")
		self.oHelper.Program('JURA219')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","31/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR04","001",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.ClickFolder("Distribuições excluídas")
		self.oHelper.ClickBox("Código","0000000002")
		self.oHelper.SetButton("Outras Ações","Restaurar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da página")
		self.oHelper.AssertTrue()

	def test_JURA219_CT009(self):

		print("CT009 - Realiza a importacao da distribuicao a partir do modelo criado")
		self.oHelper.Program('JURA219')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","31/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR04","001",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.ClickFolder("Campos Obrigatórios")
		self.oHelper.SetButton("Carregar Modelo")
		self.oHelper.SetButton("Sim")
		self.oHelper.SearchBrowse("JURA219 - MODELO CT003", key=3, index=True)
		self.oHelper.SetButton("Confirma")
		self.oHelper.ClickFolder("Resumo")
		self.oHelper.ClickGridCell("Código",row=1)
		self.oHelper.ClickBox("Código","0000000001")
		self.oHelper.SetButton("Importar")
		self.oHelper.WaitProcessing("Processando...")
		self.oHelper.SetValue("NTA_CTIPO","00006")
		self.oHelper.SetValue("NTA_DTFLWP","31/10/2040")
		self.oHelper.ClickGridCell("Sigla part",row=1)
		self.oHelper.SetValue("NTE_SIGLA","CRS",grid=True)
		self.oHelper.LoadGrid()
		self.oHelper.SetButton("Confirmar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da Página")
		self.oHelper.SetLateralMenu("Atualizações > Assuntos Jurídicos > Pesquisas")
		self.oHelper.SetValue("cValor","Contencioso",name_attr=True)
		self.oHelper.WaitFieldValue("NSZ_CCLIEN","")
		self.oHelper.SetValue("NSZ_CCLIEN","JUR219")
		self.oHelper.ClickLabel("Pesquisar")
		self.oHelper.ClickGridCell("Código do cliente",row=1)
		self.oHelper.ClickLabel("Visualizar")
		self.oHelper.CheckResult("NSZ_NUMPRO","50029490320188130693")
		self.oHelper.SetButton("Anexos")
		self.oHelper.ClickBox("Descricao","instrucoespdf.pdf")
		self.oHelper.SetButton("Exportar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Follow-ups")
		self.oHelper.SetButton("Visualizar")
		self.oHelper.CheckResult("NTA_CTIPO","00006")
		self.oHelper.CheckResult("NTA_DTFLWP","31/10/2040")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("X")
		self.oHelper.SetButton("Fechar")
		self.oHelper.ClickLabel("Sair")
		self.oHelper.AssertTrue()

	def test_JURA219_CT010(self):

		print("CT010 - Realiza a importacao manual da distribuicao")
		self.oHelper.Program('JURA219')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","31/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR04","001",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.ClickFolder("Resumo")
		self.oHelper.ClickGridCell("Código",row=1)
		self.oHelper.ClickBox("Código","0000000002")
		self.oHelper.SetButton("Outras Ações","Importar Manual")
		self.oHelper.WaitProcessing("Processando...")
		self.oHelper.SetButton("Fechar",check_error=False)
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da página")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da página")
		self.oHelper.AssertTrue()

	def test_JURA219_CT011(self):
		
		print("CT011 - Realiza a importacao da distribuicao como incidente")
		self.oHelper.Program('JURA219')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","01/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","31/10/2018",name_attr=True)
		self.oHelper.SetValue("MV_PAR04","001",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		#Carrega o modelo
		self.oHelper.ClickFolder("Campos Obrigatórios")
		self.oHelper.SetButton("Carregar Modelo")
		self.oHelper.SetButton("Sim")
		self.oHelper.SearchBrowse("JURA219 - MODELO CT003", key=3, index=True)
		self.oHelper.SetButton("Confirma")
		#Selecioa a distribuição para importar
		self.oHelper.ClickFolder("Resumo")
		self.oHelper.ClickGridCell("Código",row=1)
		self.oHelper.ClickBox("Código","0000000003")
		self.oHelper.SetButton("Outras Ações","Importar Incidente")
		self.oHelper.WaitProcessing("Processando...")
		
		#Seleciona o processo para vincular como incidente
		self.oHelper.SetValue("cClient","JUR219",name_attr=True)
		self.oHelper.SetButton("Pesquisar")
		self.oHelper.ClickGridCell("Num.Processo",row=1)
		self.oHelper.ClickBox("Num.Processo")
		self.oHelper.SetButton("Ok")

		#Prenche o FUP
		self.oHelper.SetValue("NTA_CTIPO","00006")
		self.oHelper.SetValue("NTA_DTFLWP","31/10/2040")
		self.oHelper.ClickGridCell("Sigla part",row=1)
		self.oHelper.SetValue("NTE_SIGLA","CRS",grid=True)
		self.oHelper.LoadGrid()
		self.oHelper.SetButton("Confirmar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Ok",check_error=False)
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da página")
		self.oHelper.AssertTrue()

	@classmethod
	def tearDownClass(inst):
		inst.oHelper.TearDown()

if __name__ == '__main__':
	unittest.main()