from tir import Webapp
import unittest

class JURA020_XML(unittest.TestCase):

	@classmethod
	def setUpClass(inst):
		inst.oHelper = Webapp()
		inst.oHelper.Setup('SIGAJURI','14/12/2020','T1','D MG 01 ','76')
		inst.oHelper.Program('JURA020')
		inst.oHelper.AddParameter("MV_JTPIMP", "", "1", "", "")
		inst.oHelper.AddParameter("MV_JPUBTOT", "", "2", "", "")
		inst.oHelper.AddParameter("MV_JNT4CLI", "", "2", "", "")
		inst.oHelper.SetParameters()

	def test_JURA020_XML_CT001(self):
		print('CT001_XML - Efetua vinculo e conciliação manual de Publicação')

		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.SetButton("Arquivo XML")
		self.oHelper.SetFilePath(r"SERVIDOR\baseline\TIR-JURA020_XML_CT001.xml",'Salvar')
		self.oHelper.SetValue("M->NR0__TPARQ","2 - Da-Justi",name_attr=True)
		self.oHelper.SetButton("Importar Arquivo")
		self.oHelper.SetButton("Outras Ações","Filtrar por Palavra-chave")
		self.oHelper.ClickBox("Palavra-Chave","SEARCHKEY_TIR_JURA020_XML")
		self.oHelper.SetButton("Filtrar")
		self.oHelper.ClickFolder("Publicações não Localizadas")
		self.oHelper.ClickBox("Num.Proc.","TIR-JURA020_XML_001")
		self.oHelper.SetButton("Outras Ações","Vincular Processo")
		self.oHelper.SetButton("Sim")
		self.oHelper.SetValue("cProces","JURA020_XML_001",name_attr=True)
		self.oHelper.SetButton("Pesquisar")
		self.oHelper.SetValue("cAutor","01",name_attr=True)
		self.oHelper.ClickGridCell("Cód.Interno",row=1)
		self.oHelper.ClickBox("Cód.Interno","0000000173")
		self.oHelper.SetButton("Ok")
		self.oHelper.SetButton("Sim")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da Página")
		self.oHelper.SetLateralMenu("Atualizações > Assuntos Jurídicos > Pesquisas")
		self.oHelper.SetValue("cValor","Contencioso",name_attr=True)
		self.oHelper.WaitFieldValue("NSZ_COD","")
		self.oHelper.SetValue("NSZ_COD","0000000173")
		self.oHelper.ClickLabel("Pesquisar")
		self.oHelper.ClickGridCell("Código do cliente",row=1)
		self.oHelper.ClickLabel("Visualizar")
		self.oHelper.CheckResult("NSZ_NUMPRO","TIR-JURA020_XML_001")
		self.oHelper.CheckResult("NSZ_COD","0000000173")
		self.oHelper.SetButton("Fechar")
		self.oHelper.ClickLabel("Sair")
		self.oHelper.SetLateralMenu("Importação de Publicações")
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","",name_attr=True)
		self.oHelper.F3(field="MV_PAR02", name_attr=True)
		self.oHelper.ScrollGrid(column="Nome Arq.", match_value="TIR-JURA020_XML_CT001.XML")
		self.oHelper.SetButton("OK")
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.SetButton("Outras Ações","Filtrar por Palavra-chave")
		self.oHelper.ClickBox("Palavra-Chave","SEARCHKEY_TIR_JURA020_XML")
		self.oHelper.SetButton("Filtrar")
		self.oHelper.ClickFolder("Publicações Localizadas")
		self.oHelper.ClickBox("Num.Proc.","TIR-JURA020_XML_001")
		self.oHelper.SetButton("Outras Ações","Conciliar Manual")
		self.oHelper.SetButton("Sim")
		self.oHelper.SetValue("cCodAto","008",name_attr=True)
		self.oHelper.SetButton("Ok")
		self.oHelper.SetButton("Ok")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Sair da Página")
		self.oHelper.SetLateralMenu("Pesquisas")
		self.oHelper.SetValue("cValor","Contencioso",name_attr=True)
		self.oHelper.WaitFieldValue("NSZ_COD","")
		self.oHelper.SetValue("NSZ_COD","0000000173")
		self.oHelper.ClickLabel("Pesquisar")
		self.oHelper.ClickGridCell("Código do cliente",row=1)
		self.oHelper.ClickLabel("Visualizar")
		self.oHelper.CheckResult("NSZ_COD","0000000173")
		self.oHelper.SetButton("Andamentos")
		self.oHelper.SetButton("Visualizar")
		self.oHelper.CheckResult("NT4_CAJURI","0000000173")
		self.oHelper.CheckResult("NT4_CATO","008")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("X")
		self.oHelper.SetButton("Fechar")
		self.oHelper.ClickLabel('Sair')
		self.oHelper.AssertTrue()

	def test_JURA020_XML_CT002(self):
		print('CT002_XML - Efetua Exclusão e restauração de Publicação')

		self.oHelper.Program('JURA020')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","0004",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.ClickFolder("Publicações não Localizadas")
		self.oHelper.ClickBox("Num.Proc","TIR-JURA020_XML_003")
		self.oHelper.SetButton("Outras Ações","Excluir")
		self.oHelper.SetButton("Sim")
		self.oHelper.ClickFolder("Publicações Excluídas")
		self.oHelper.ClickBox("Num.Proc","TIR-JURA020_XML_003")
		self.oHelper.SetButton("Outras Ações","Restaurar")
		self.oHelper.SetButton("Sim")
		self.oHelper.ClickFolder("Publicações não Localizadas")
		self.oHelper.ClickBox("Num.Proc","TIR-JURA020_XML_003")
		self.oHelper.SetButton("Confirmar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.AssertTrue()

	def test_JURA020_XML_CT003(self):
		print('CT003_XML - Efetua exportação do relatório de Publicação')

		self.oHelper.Program('JURA020')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","0004",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.SetButton("Outras Ações","Exportar Publicações")
		self.oHelper.WaitShow("Arquivo gerado com sucesso, caminho")
		self.oHelper.SetButton("Fechar")
		self.oHelper.SetButton("Confirmar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.AssertTrue()

	def test_JURA020_XML_CT004(self):
		print('CT004_XML - Efetua importação de publicação através do XML Destaque')

		self.oHelper.Program('JURA020')
		self.oHelper.SetButton("Perguntas")
		self.oHelper.SetValue("MV_PAR01","",name_attr=True)
		self.oHelper.SetValue("MV_PAR02","",name_attr=True)
		self.oHelper.SetButton("Informações")
		self.oHelper.SetButton("Executar")
		self.oHelper.SetButton("Arquivo XML")
		self.oHelper.SetFilePath(r"SERVIDOR\baseline\TIR-JURA020_XML-Destaque.xml",'Salvar')
		self.oHelper.SetValue("M->NR0__TPARQ","3 - Destaque",name_attr=True)
		self.oHelper.SetButton("Importar Arquivo")
		self.oHelper.ClickFolder("Publicações Localizadas")
		self.oHelper.ClickBox("Num.Proc","00130612520178260068")
		self.oHelper.SetButton("Confirmar")
		self.oHelper.SetButton("Fechar")
		self.oHelper.AssertTrue()
		self.oHelper.RestoreParameters()
	@classmethod
	def tearDownClass(inst):
		inst.oHelper.TearDown()

if __name__ == '__main__':
	unittest.main()
