import unittest

from tir.technologies.apw_internal import ApwInternal


class PPLCHAPRE03TESTCASE(unittest.TestCase):

    # test_PPLCHAPRE03_CT001 - Atendimento Solicitação de internação Autorizada com impressão
    # test_PPLCHAPRE03_CT002 - Atendimento Solicitação de internação Pacialmente Autorizada com Impressão
    # test_PPLCHAPRE03_CT003 - Atendimento Solicitação de internação Negada
    # test_PPLCHAPRE03_CT004 - Atendimento Solicitação de internação Em Auditoria com inclusão de documentos

    @classmethod
    def setUpClass(inst):

        inst.oHelper = ApwInternal("config.json")

        inst.oHelper.Setup()

    def test_PPLCHAPRE03_CT001(self):

        self.oHelper.ClickMenu("Principal > Atendimento")
        self.oHelper.ClickLink("Trocar para matrícula")
        self.oHelper.SetValue("Selecione o prestador, local de Atendimento e regime de atendimento que irá atender o beneficiário", "HOSPITAL BOM CLIMA - HOSPITAIS - NORMAL")
        self.oHelper.SetValue("Matrícula", "00010013000001003")
        self.oHelper.SetButton("Confirmar")
        self.oHelper.SwitchModal("Fechar")
        self.oHelper.SetValue("Tipo de Atendimento:", "Internacao")
        self.oHelper.SelectBrowse("CARLOS ROBERTO|HOSPITAL BOM CLIMA")
        self.oHelper.SetButton("Atendimento")
        self.oHelper.SetButton("000 - Protocolo", "add")
        self.oHelper.SetValue("009 - Rn?", "Nao")
        self.oHelper.SetButton("014 - Nome Prof. Sol.", "search")
        self.oHelper.SearchValue("Numero C.R.", "654987")
        self.oHelper.SetValue("018 - Cbos", "MEDICO EM GERAL (CLINICO GERAL)")
        self.oHelper.SetButton("022 - Car. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetButton("023 - Tp. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetButton("024 - Reg. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetValue("025 - Qtd. Diarias Sol.", "1")
        self.oHelper.SetValue("026 - Previsao Opme?", "Nao")
        self.oHelper.SetValue("027 - Previsao Quimio?", "Nao")
        self.oHelper.SetValue("028 - Indicacao Clinica", "Teste internação autorizada")
        self.oHelper.SetButton("033 - Ind. Acidente", "search")
        self.oHelper.SearchValue("Código", "9")
        self.oHelper.SetButton("035 - Codigo Procedimento", "search")
        self.oHelper.SearchValue("Código", "40303136", True)
        self.oHelper.SetValue("037 - Qtd Sol.", "5", True)
        self.oHelper.SetGrid()
        self.oHelper.SetButton("Confirmar")
        self.oHelper.WaitModal("Autorizada")
        self.oHelper.SwitchModal("Fechar")
        self.oHelper.SetButton("imprimir")
        self.oHelper.SwitchWindow()
        self.oHelper.CheckLink("Clique aqui.")
        self.oHelper.CloseWindow()
        self.oHelper.SwitchWindow()
        self.oHelper.SetButton("Anexar documento")
        self.oHelper.SetValue("Selecione o Arquivo:", "C:\\Totvs\\Automacao\\UPLOAD_GEN.txt")
        self.oHelper.SetButton("Anexar")
        self.oHelper.CheckBrowse("UPLOAD_GEN")
        self.oHelper.EndCase()

    def test_PPLCHAPRE03_CT002(self):

        self.oHelper.ClickMenu("Principal > Atendimento")
        self.oHelper.SetValue("Tipo de Atendimento:", "Internacao")
        self.oHelper.SelectBrowse("CARLOS ROBERTO|HOSPITAL BOM CLIMA")
        self.oHelper.SetButton("Atendimento")
        self.oHelper.SetButton("000 - Protocolo", "add")
        self.oHelper.SetValue("009 - Rn?", "Nao")
        self.oHelper.SetButton("014 - Nome Prof. Sol.", "search")
        self.oHelper.SearchValue("Numero C.R.", "654987")
        self.oHelper.SetValue("018 - Cbos", "MEDICO EM GERAL (CLINICO GERAL)")
        self.oHelper.SetButton("022 - Car. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetButton("023 - Tp. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetButton("024 - Reg. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetValue("025 - Qtd. Diarias Sol.", "1")
        self.oHelper.SetValue("026 - Previsao Opme?", "Nao")
        self.oHelper.SetValue("027 - Previsao Quimio?", "Nao")
        self.oHelper.SetValue("028 - Indicacao Clinica", "Teste internação autorizada")
        self.oHelper.SetButton("033 - Ind. Acidente", "search")
        self.oHelper.SearchValue("Código", "9")
        self.oHelper.SetButton("035 - Codigo Procedimento", "search")
        self.oHelper.SearchValue("Código", "40303136", True)
        self.oHelper.SetValue("037 - Qtd Sol.", "1", True)
        self.oHelper.SetGrid()
        self.oHelper.SetButton("035 - Codigo Procedimento", "search")
        self.oHelper.SearchValue("Código", "40311236", True)
        self.oHelper.SetValue("037 - Qtd Sol.", "1", True)
        self.oHelper.SetGrid()
        self.oHelper.SwitchModal("Fechar")
        self.oHelper.SetButton("Confirmar")
        self.oHelper.WaitModal("Autorizada Parcialmente")
        self.oHelper.SwitchModal("Fechar")
        self.oHelper.SetButton("imprimir")
        self.oHelper.SwitchWindow()
        self.oHelper.CheckLink("Clique aqui.")
        self.oHelper.CloseWindow()
        self.oHelper.SwitchWindow()
        self.oHelper.SetButton("Anexar documento")
        self.oHelper.SetValue("Selecione o Arquivo:", "C:\\Totvs\\Automacao\\UPLOAD_GEN.txt")
        self.oHelper.SetButton("Anexar")
        self.oHelper.CheckBrowse("UPLOAD_GEN")
        self.oHelper.EndCase()

    def test_PPLCHAPRE03_CT003(self):

        self.oHelper.ClickMenu("Principal > Atendimento")
        self.oHelper.SetValue("Tipo de Atendimento:", "Internacao")
        self.oHelper.SelectBrowse("CARLOS ROBERTO|HOSPITAL BOM CLIMA")
        self.oHelper.SetButton("Atendimento")
        self.oHelper.SetButton("000 - Protocolo", "add")
        self.oHelper.SetValue("009 - Rn?", "Nao")
        self.oHelper.SetButton("014 - Nome Prof. Sol.", "search")
        self.oHelper.SearchValue("Numero C.R.", "654987")
        self.oHelper.SetValue("018 - Cbos", "MEDICO EM GERAL (CLINICO GERAL)")
        self.oHelper.SetButton("022 - Car. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetButton("023 - Tp. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetButton("024 - Reg. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetValue("025 - Qtd. Diarias Sol.", "1")
        self.oHelper.SetValue("026 - Previsao Opme?", "Nao")
        self.oHelper.SetValue("027 - Previsao Quimio?", "Nao")
        self.oHelper.SetValue("028 - Indicacao Clinica", "Teste internação autorizada")
        self.oHelper.SetButton("033 - Ind. Acidente", "search")
        self.oHelper.SearchValue("Código", "9")
        self.oHelper.SetButton("035 - Codigo Procedimento", "search")
        self.oHelper.SearchValue("Código", "40311236", True)
        self.oHelper.SetValue("037 - Qtd Sol.", "1", True)
        self.oHelper.SetGrid()
        self.oHelper.SwitchModal("Fechar")
        self.oHelper.SetButton("Confirmar")
        self.oHelper.WaitModal("Nao Autorizada")
        self.oHelper.SwitchModal("Fechar")
        self.oHelper.SetButton("Anexar documento")
        self.oHelper.SetValue("Selecione o Arquivo:", "C:\\Totvs\\Automacao\\UPLOAD_GEN.txt")
        self.oHelper.SetButton("Anexar")
        self.oHelper.CheckBrowse("UPLOAD_GEN")
        self.oHelper.EndCase()

    def test_PPLCHAPRE03_CT004(self):

        self.oHelper.ClickMenu("Principal > Atendimento")
        self.oHelper.SetValue("Tipo de Atendimento:", "Internacao")
        self.oHelper.SelectBrowse("CARLOS ROBERTO|HOSPITAL BOM CLIMA")
        self.oHelper.SetButton("Atendimento")
        self.oHelper.SetButton("000 - Protocolo", "add")
        self.oHelper.SetValue("009 - Rn?", "Nao")
        self.oHelper.SetButton("014 - Nome Prof. Sol.", "search")
        self.oHelper.SearchValue("Numero C.R.", "654987")
        self.oHelper.SetValue("018 - Cbos", "MEDICO EM GERAL (CLINICO GERAL)")
        self.oHelper.SetButton("022 - Car. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetButton("023 - Tp. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetButton("024 - Reg. Internacao", "search")
        self.oHelper.SearchValue("Código", "1")
        self.oHelper.SetValue("025 - Qtd. Diarias Sol.", "1")
        self.oHelper.SetValue("026 - Previsao Opme?", "Nao")
        self.oHelper.SetValue("027 - Previsao Quimio?", "Nao")
        self.oHelper.SetValue("028 - Indicacao Clinica", "Teste internação autorizada")
        self.oHelper.SetButton("033 - Ind. Acidente", "search")
        self.oHelper.SearchValue("Código", "9")
        self.oHelper.SetButton("035 - Codigo Procedimento", "search")
        self.oHelper.SearchValue("Código", "30101018", True)
        self.oHelper.SetValue("037 - Qtd Sol.", "1", True)
        self.oHelper.SetGrid()
        self.oHelper.SwitchModal("Fechar")
        self.oHelper.SetButton("Confirmar")
        self.oHelper.WaitModal("Em Análise")
        self.oHelper.SwitchModal("Fechar")
        self.oHelper.SetButton("Anexar documento")
        self.oHelper.SetValue("Selecione o Arquivo:", "C:\\Totvs\\Automacao\\UPLOAD_GEN.txt")
        self.oHelper.SetButton("Anexar")
        self.oHelper.CheckBrowse("UPLOAD_GEN")
        self.oHelper.EndCase()

    @classmethod
    def tearDownClass(inst):
        '''
        Método que finaliza o TestCase
        '''
        inst.oHelper.TearDown()


if __name__ == '__main__':
    unittest.main()
