from tir import Webapp
import unittest

class OGA250(unittest.TestCase):

	@classmethod
	def setUpClass(inst):                
		from datetime import datetime
		DateSystem = datetime.today().strftime('%d/%m/%Y')
		
		inst.oHelper = Webapp()                
		inst.oHelper.Setup('SIGAAGR',DateSystem,'T1','D MG 01 ')                                
		
	def test_OGA250_CT001(self):                                        
		#Cenário 001: Entrada por produção - nova comercialização                
		self.oHelper.Program('OGA250')                
		self.oHelper.AddParameter("MV_AGRA001", "", ".T.", ".T.", ".T.")
		self.oHelper.AddParameter("MV_AGRO002", "", ".T.", ".T.", ".T.")
		self.oHelper.AddParameter("MV_SIGAAGR","",".T.",".T.",".T.")
		self.oHelper.AddParameter("MV_ARM251A", "", "001", "001", "001")
		self.oHelper.AddParameter("MV_AGRTMPR", "", "010", "010", "010")
		self.oHelper.AddParameter("MV_AGRTMPS", "", "001", "001", "001")
		self.oHelper.AddParameter("MV_AGRTMRQ", "", "501", "501", "501")
		self.oHelper.SetParameters()        
		self.oHelper.WaitShow("Romaneios com Pesagem")
		self.oHelper.SetKey("F12")
		self.oHelper.SetValue("MV_PAR01", "000001", name_attr=True)
		self.oHelper.SetButton("Ok")
		self.oHelper.SetButton("Incluir")
		self.oHelper.SetButton("Ok")
		self.oHelper.SetValue("Tipo", "1")
		self.oHelper.SetValue("Cod.Entidade", "000001")
		self.oHelper.SetValue("Loj.Entidade", "01")
		self.oHelper.ClickFolder("Analise")
		self.oHelper.SetValue("Cod. Safra", "1920")
		self.oHelper.SetValue("Cod. Produto", "AGR-FARDAO-ALGODAO")
		self.oHelper.SetValue("Local",   "01")
		self.oHelper.SetValue("Fazenda", "01")
		self.oHelper.SetValue("Un. Benef.", "01")
		self.oHelper.SetButton("Outras Ações", "Vincular Fardões")         
		self.oHelper.ClickBox("Código","000033", grid_number=1)
		self.oHelper.SetButton(">>")
		self.oHelper.SetButton("Salvar")        
		self.oHelper.SetButton("Outras Ações", "Pesagem")   
		self.oHelper.SetValue("nPeso", "1000", name_attr=True)      
		self.oHelper.SetButton("Confirmar")        
		self.oHelper.SetButton("Outras Ações", "Pesagem")   
		self.oHelper.SetValue("nPeso", "101000", name_attr=True)      
		self.oHelper.SetButton("Confirmar")        
		self.oHelper.SetButton("Confirmar")        
		self.oHelper.SetButton("Fechar")        
		self.oHelper.SetButton("Outras Ações", "Atualizar")        
		self.oHelper.SetButton("Sim")        
		self.oHelper.SetButton("Outras Ações", "Confirmar")        
		self.oHelper.WaitHide("Aguarde")

		self.oHelper.SetButton("Visualizar")   
		self.oHelper.ClickFolder("Pesagem")
		self.oHelper.CheckResult("NJJ_PSSUBT", "100.000,00")             
		self.oHelper.ClickFolder("Controle")        
		self.oHelper.CheckResult("NJJ_STATUS", "3 - Confirmado")     
		self.oHelper.AssertTrue()        
		self.oHelper.SetButton("Fechar")  
		self.oHelper.SetButton("x")        
		
	def test_OGA250_CT002(self):                    
		#Cenário 002: Exclusão documento de saída e reabertura do romaneio (atualizado)          
		self.oHelper.SetLateralMenu("Atualizações > Gestão Agrícola > Faturamento > Exclus. Doc. Saída")      
		###self.oHelper.Program("MATA521A")                
		self.oHelper.AddParameter("MV_SIGAAGR","",".T.",".T.",".T.")        
		self.oHelper.SetParameters()        
		self.oHelper.SetValue("Modelo de Interface ?"   ,"Marcacao")
		self.oHelper.SetValue("Selecionar itens ?"      ,"Nao")
		self.oHelper.SetValue("Dt.Emissao de ?"         ,"01/01/2000")
		self.oHelper.SetValue("Dt.Emissao ate ?"        ,"31/12/2045")
		self.oHelper.SetValue("Serie de ?"              ,"001")
		self.oHelper.SetValue("Serie ate ?"             ,"001")
		self.oHelper.SetValue("Documento de ?"          ,"T2501K")
		self.oHelper.SetValue("Documento ate ?"         ,"T2501K")
		self.oHelper.SetButton("OK")          
		
		self.oHelper.ClickBox("Numero","T2501K")
		self.oHelper.SetButton("Outras Ações","Excluir")
		self.oHelper.SetButton("Sim")
		self.oHelper.WaitProcessing("Estorno dos documentos de saida")
		self.oHelper.SetButton("x")                
		
		self.oHelper.Program('OGA250')                
		self.oHelper.SearchBrowse("D MG 01 0000000135", "Filial+cod.romaneio")  
		self.oHelper.SetButton("Visualizar")
		self.oHelper.ClickFolder("Controle")
		self.oHelper.CheckResult("NJJ_STATUS", "2 - Atualizado")     
		self.oHelper.AssertTrue()  
		self.oHelper.SetButton("Fechar")  
		self.oHelper.SetButton("x")        
		 
	def test_OGA250_CT003(self):                            
		#Cenário 003: Exclusão documento de saída e reabertura do romaneio (atualizado)   
		self.oHelper.SetLateralMenu("Atualizações > Gestão Agrícola > Faturamento > Exclus. Doc. Saída")              
		#self.oHelper.Program("MATA521A")        
		self.oHelper.AddParameter("MV_SIGAAGR","",".T.",".T.",".T.")        
		self.oHelper.SetParameters()        
		self.oHelper.SetValue("Modelo de Interface ?"   ,"Marcacao")
		self.oHelper.SetValue("Selecionar itens ?"      ,"Nao")
		self.oHelper.SetValue("Dt.Emissao de ?"         ,"01/01/2000")
		self.oHelper.SetValue("Dt.Emissao ate ?"        ,"31/12/2045")
		self.oHelper.SetValue("Serie de ?"              ,"001")
		self.oHelper.SetValue("Serie ate ?"             ,"001")
		self.oHelper.SetValue("Documento de ?"          ,"T2501L")
		self.oHelper.SetValue("Documento ate ?"         ,"T2501L")
		self.oHelper.SetButton("OK")          
		
		self.oHelper.ClickBox("Numero","T2501L")
		self.oHelper.SetButton("Outras Ações","Excluir")
		self.oHelper.SetButton("Sim")
		self.oHelper.WaitProcessing("Estorno dos documentos de saida")        
		self.oHelper.SetButton("x")                
		
		self.oHelper.Program('OGA250')      
		self.oHelper.SearchBrowse("D MG 01 0000000136", "Filial+cod.romaneio")  
		self.oHelper.SetButton("Visualizar")
		self.oHelper.ClickFolder("Controle")
		self.oHelper.CheckResult("NJJ_STATUS", "2 - Atualizado")     
		self.oHelper.AssertTrue()    
		self.oHelper.SetButton("Fechar")  
		self.oHelper.SetButton("x")        
			 
	def test_OGA250_CT004(self):    #cenario exclusão doc entrada         
		#Cenário 004: Exclusão documento de entrada e reabertura do romaneio (atualizado)                        
		self.oHelper.Program('MATA103')		
		self.oHelper.AddParameter("MV_SIGAAGR","",".T.",".T.",".T.")        
		self.oHelper.SetParameters()        
		self.oHelper.SearchBrowse("D MG 01 T25023", "Filial+numero")
		self.oHelper.SetButton('Outras Ações', "Excluir")
		self.oHelper.SetButton("Confirmar")                  
		self.oHelper.SetButton("x")                
		
		self.oHelper.Program('OGA250')                
		self.oHelper.SearchBrowse("D MG 01 0000000147", "Filial+cod.romaneio")  
		self.oHelper.SetButton("Visualizar")
		self.oHelper.ClickFolder("Controle")
		self.oHelper.CheckResult("NJJ_STATUS", "2 - Atualizado")     
		self.oHelper.AssertTrue()    
		self.oHelper.SetButton("Fechar")  
		self.oHelper.SetButton("x")        

	def test_OGA250_CT005(self):                                        
		#Cenário 005: Expedição Algodão sem IE - Novo Negócio
		if self.oHelper.GetRelease() >= "12.1.028":
			self.oHelper.Program('OGA250')                
			self.oHelper.AddParameter("MV_AGRA001", "", ".T.", ".T.", ".T.")
			self.oHelper.AddParameter("MV_AGRO002", "", ".T.", ".T.", ".T.")        
			self.oHelper.AddParameter("MV_SIGAAGR", "", ".T.", ".T.", ".T.")        
			self.oHelper.AddParameter("MV_OGDECPS", "", "2", "2", "2")        
			self.oHelper.AddParameter("MV_AGRTMPP", "", "501", "501", "501")        
			self.oHelper.SetParameters()        
			self.oHelper.WaitShow("Romaneios com Pesagem")
			self.oHelper.SearchBrowse("D MG 01 0000000154", "Filial+cod.romaneio")  
			self.oHelper.SetButton("Alterar")        
			self.oHelper.ClickFolder("Comercialização")

			self.oHelper.SetValue("Intervalo", "001", grid=True)
			self.oHelper.SetValue("Id Regra",  "002", grid=True)
			self.oHelper.LoadGrid()
			self.oHelper.SetButton("Confirmar")
			self.oHelper.SetButton("Fechar")
			self.oHelper.SetButton("Outras Ações","Vincular Fardos")        
			self.oHelper.ClickBox("Filial",select_all=True, grid_number=1)
			self.oHelper.SetButton(">>")
			self.oHelper.SetButton("Salvar")
			self.oHelper.SetButton("Outras Ações","Atualizar")
			self.oHelper.SetButton("Sim")
			self.oHelper.SetButton("Outras Ações","Confirmar")
			self.oHelper.WaitShow("Serie / Notas")
			self.oHelper.SetButton("Ok")
			self.oHelper.SetButton("Ok")
			self.oHelper.SetButton("Cancelar")
			self.oHelper.SetButton("Visualizar")
			self.oHelper.ClickFolder("Controle")
			self.oHelper.CheckResult("NJJ_STATUS", "3 - Confirmado")     
			self.oHelper.AssertTrue()        
			self.oHelper.SetButton("Fechar")  
			self.oHelper.SetButton("x")      
					  
	@classmethod
	def tearDownClass(inst):
		inst.oHelper.TearDown()

if __name__ == '__main__':
	unittest.main()

